stdout of test 'tst303` in directory 'src/mal` itself:
# Monet Database Server V5.0
# Copyright (c) 1993-2004, CWI. All rights reserved.
# compiled for 32biti686-pc-linux-gnu/32bit.
# config:/ufs/mk/monet5/src/mal/Tests/tst.conf
# dbfarm:/ufs/mk/monet5/Linux/var/MonetDB/dbfarm
# dbname:demo
# Visit http://monetdb.cwi.nl for further information.
## recursively raise an exception passed upward
#raise	IllegalAccess := "an exception";
#	print("should not come here\n");
#catch	IllegalAccess;
#	printf("catched %s\n",IllegalAccess);
#raise	IllegalAccess:= "a second exception raised\n";
#	print("should not come here either\n");
#exit	IllegalAccess;
#	print("should not be done");
#
function Admin.main():int;	# 0  (main:int)
    raise IllegalAccess := "an exception";	# 1  (IllegalAccess:str)<-($2:str)
    io.print("should not come here\n");	# 2 IOprint_val ($3:int)<-($4:str)
catch IllegalAccess;	# 3  (IllegalAccess:str) jump 7
    io.printf("catched %s\n",IllegalAccess);	# 4 IOprint_formatted_str ($5:int)<-($6:str)(IllegalAccess:str)
    raise IllegalAccess := "a second exception raised\n";	# 5  (IllegalAccess:str)<-($7:str)
    io.print("should not come here either\n");	# 6 IOprint_val ($8:int)<-($9:str)
exit IllegalAccess;	# 7  (IllegalAccess:str)
    io.print("should not be done");	# 8 IOprint_val ($10:int)<-($11:str)
end main;	# 9  
catched an exception
!ERROR: a second exception raised\nMALexception:Admin.main[9]: propagated
>