#testing exceptions raised in the kernel

b:= new(:int,:int);
z:= find(b,0);
print("should not come here anymore");
catch MALexception;
	print("catched the exception");
exit MALexception;
